version: '3.1'

services:

  osrm-backend:
    container_name: alsace_osrm-backend-prod
    ports:
      - ${OSRM_PORT}:5000
    volumes:
      - osrm:/data
    build:
      context: .
      dockerfile: Dockerfile.osrm

  mariadb:
    container_name: alsace_mariadb-prod
    image: dalidos/alsace:mariadb
    expose:
      - ${DB_PORT}

  server:
    depends_on:
      - mariadb
    container_name: alsace_server-prod
    image: dalidos/alsace:server
    ports:
      - ${PORT_EXPRESS}:${PORT_EXPRESS}

  client:
    container_name: alsace_client-prod
    image: dalidos/alsace:client
    depends_on:
      - server
    ports:
      - ${PORT_ANGULAR}:8100

volumes:
  dbdata:
  mysql: {}
  osrm:
