version: '3.1'

services:

  osrm-backend:
    container_name: alsace_osrm-backend
    ports:
      - ${OSRM_PORT}:5000
    volumes:
      - osrm:/data
    build:
      context: ./docker/osrm/
      dockerfile: Dockerfile

  mariadb:
    container_name: alsace_mariadb
    ports:
      - 3306:3306
    build:
      context: .
      dockerfile: docker/mariadb/Dockerfile
#    image: dalidos/alsace:mariadb
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=alsace
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=rowenta
    expose:
      - 3306

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    container_name: alsace_phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: mariadb:3306
      MYSQL_ROOT_PASSWORD: root
    links:
      - mariadb

  server:
    depends_on:
      - mariadb
    container_name: alsace_server
    restart: always
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    #    image: dalidos/alsace:server
    volumes:
      - .:/app
    ports:
      - ${PORT_EXPRESS}:${PORT_EXPRESS}

  client:
    container_name: alsace_client
    build:
      context: ./client
      dockerfile: ../docker/client/Dockerfile
    #    image: dalidos/alsace:client
    volumes:
      - .:/app
    ports:
      - 80:8100
    depends_on:
      - server

volumes:
  dbdata:
  mysql: {}
  osrm:
